name: Java CI with Maven and CodeQL analyze

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches: [ master ]

jobs:

  analyze_and_build:

    name: Analyze and Build
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Initialize CodeQL with v3 (updated)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: ./book-portal-be

      # Perform CodeQL Analysis with v3 (updated)
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  docker:

    needs: analyze_and_build
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_TWO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push BE
        uses: docker/build-push-action@v4
        with:
          context: ./book-portal-be
          file: ./book-portal-be/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-be:latest
          platforms: linux/amd64
