env:
  CI: false

name: Node.js CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: NodeJS Install and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Updated from 17.x to 18.x

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Updated from v2 to v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './book-portal-fe/package-lock.json'

    # Add retry logic and use npm registry directly
    - name: Clean npm cache
      run: npm cache clean --force
      working-directory: ./book-portal-fe
      continue-on-error: true

    - name: Install dependencies
      run: |
        npm ci --prefer-offline --no-audit --registry=https://registry.npmjs.org/
      working-directory: ./book-portal-fe
      env:
        NPM_CONFIG_REGISTRY: https://registry.npmjs.org/

    - name: Build application
      run: npm run build --if-present
      working-directory: ./book-portal-fe


  docker:

    needs: build
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Updated from v1 to v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated from v1 to v2

      - name: Build and push FE
        uses: docker/build-push-action@v4  # Updated from v2 to v4
        with:
          context: ./book-portal-fe
          file: ./book-portal-fe/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-fe:latest

      - name: Build and push Nginx
        uses: docker/build-push-action@v4  # Updated from v3 to v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-proxy:latest
